services:

  # 前端服务 - 使用宿主机网络模式测试
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.simple
    container_name: chat-sales-frontend
    # 使用宿主机网络模式 (Windows可能不完全支持)
    network_mode: "host"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf 