server:
  port: 8092
  servlet:
    context-path: /chat_gpt_demo

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/ds_test?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&characterEncoding=utf8&useUnicode=true
    username: ds_test
    password: ds_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
  main:
    lazy-initialization: false
    allow-bean-definition-overriding: true

# DeepSeek API配置
deepseek:
  api-key: ${DEEPSEEK_API_KEY:sk-93432e44cb8545a78ebc85b718157109}
  model: deepseek-chat

# JWT配置
jwt:
  secret: rRHrJ96$^7aZ!cSpBUw5f%PvN3G2k#xEqL8yDtQmYs*Vh@WzK4j&dF
  expiration: 7200000  # 2小时(毫秒)
  refresh-expiration: 604800000  # 7天(毫秒)

# 自定义应用配置
app:
  sync:
    enabled: true

# 跨域配置
cors:
  allowed-origins:
    - http://localhost:3003
    - http://frontend:3003
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    root: info
    org.hibernate.SQL: info
    com.example.chatsales: debug
    com.example.chatsales.scheduled: info
    org.springframework.jdbc.core: info
    org.springframework.scheduling: debug
    com.zaxxer.hikari.HikariConfig: debug
  file:
    name: /app/logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# SQL Server 数据源配置
sqlserver:
  datasource:
    jdbc-url: jdbc:sqlserver://host.docker.internal:11433;databaseName=sourcedb
    username: sa
    password: Passw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      minimum-idle: 0
      maximum-pool-size: 10
      idle-timeout: 60000
      max-lifetime: 1800000

# 日志配置
logging:
  level:
    root: info
    org.hibernate.SQL: debug
    com.example.chatsales: debug
    com.example.chatsales.scheduled: info  # 定时任务日志
    org.springframework.jdbc.core: debug
    org.springframework.scheduling: debug  # Spring定时任务框架日志
    com.zaxxer.hikari: debug  # 添加HikariCP日志以便调试
  file:
    name: /app/logs/application.log  # 明确指定日志文件位置
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 