server:
  port: 8089
  servlet:
    context-path: /chat_gpt_demo  # 明确设置上下文路径为根目录

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ds_test?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ds_test
    password: ds_test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    enabled: false  # 禁用Flyway自动迁移
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
  main:
    lazy-initialization: false  # 全局懒加载设置为false
    allow-bean-definition-overriding: true

# DeepSeek API配置
deepseek:
  api-key: ${DEEPSEEK_API_KEY:sk-93432e44cb8545a78ebc85b718157109}
  model: deepseek-chat

# JWT配置
jwt:
  secret: rRHrJ96$^7aZ!cSpBUw5f%PvN3G2k#xEqL8yDtQmYs*Vh@WzK4j&dF
  expiration: 7200000  # 2小时(毫秒)
  refresh-expiration: 604800000  # 7天(毫秒)

# 自定义应用配置
app:
  sync:
    enabled: true  # 启用数据同步定时任务

logging:
  level:
    root: info
    org.hibernate.SQL: info
    com.example.chatsales: debug
    com.example.chatsales.scheduled: info  # 定时任务日志
    org.springframework.jdbc.core: info
    org.springframework.scheduling: debug  # Spring定时任务框架日志
    com.zaxxer.hikari.HikariConfig: debug  # 添加HikariCP日志以便调试
  file:
    name: /app/logs/application.log  # 明确指定日志文件位置
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 